### ISSUE TITLE
USB_cam configuration

### ISSUE THREAD

**Issue by binhkhongbeo** [Tinker-Twins/AprilTag-ROS-1#1]
Hi Tinker-Twins
I found your project in Youtube and I really like it. I want to apply this to my little project but I don't know how to reconfig the usb_cam package cause my camera is different (intel realsense d435). Can you guide me through so that I can run the project with various kind of usb camera, please?
Your Project is great by the way. Thanks alot, hope to hear from you.

**Comment by Tinker-Twins** [comment]
Thank you for your appreciation!

Regarding your questions, although we have personally not tested detection with RealSense cameras yet, it should be quite straightforward.

For ROS check out: [https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqazlkZTF3MmhBeDZIVUNaWEpTV1BYNEV5Z2FGd3xBQ3Jtc0tuTXBfbmNmRmNKaVg3Z054QzFpTUNLakFXWV9KeU5EUzlodjRSb0NzOXpIRlZNUUEzUzU2Wlp1c05PUlFZTXpmMEd6bHl0cnBZQllOVGdZRFI2aVdQNFBXQWM0cDJCQkJuQzRPbFRlOTRqYWJqZTctWQ&q=https%3A%2F%2Fgithub.com%2FIntelRealSense%2Frealsense-ros%2Ftree%2Fros1-legacy&stzid=Ugyncirf_KvRWw93jGN4AaABAg.9yAP6rykiSf9yEJ__Rs8Js)

For ROS 2 checkout:
[https://github.com/IntelRealSense/realsense-ros/tree/ros2-development](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqa2tHYWhtclJWYXMtVVJ1QlRSdTFZVVNRY3V6d3xBQ3Jtc0tsY1UwWFJScHJ3bnJoN2U3YjNNZW5QS05wa1JRV19EbEdNRGhzUVZ4aDFfaENQTEU3UFNzOUdveDZibnMzWW40ZHMtMGFoOV91R3MyR0ozTE4wd2g4VGZfWnBXS0pyX1R5d2kwel9JU1VaRlVJSzg3UQ&q=https%3A%2F%2Fgithub.com%2FIntelRealSense%2Frealsense-ros%2Ftree%2Fros2-development&stzid=Ugyncirf_KvRWw93jGN4AaABAg.9yAP6rykiSf9yEJ__Rs8Js)
OR
[https://github.com/IntelRealSense/realsense-ros/tree/ros2-legacy](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqa0Q1VmFPcm5wWnZ5c0pUQnJYWm9WeG9LVVU5UXxBQ3Jtc0trV2ktdDNLQU5OS1BkRmo4NEs4djdYZTRqTHB0c0U4aWIxZWRfdEZsMnlLSXJabHBHOFBxRkt0VjZabEhUYXUwSGpuMzI3bElmVEd6aGMtakp3WmR1VzFxcVBjNWYyQXlmNU5acmFZalZDVUdjRmUwWQ&q=https%3A%2F%2Fgithub.com%2FIntelRealSense%2Frealsense-ros%2Ftree%2Fros2-legacy&stzid=Ugyncirf_KvRWw93jGN4AaABAg.9yAP6rykiSf9yEJ__Rs8Js)

Make sure to remap the topics to appropriate names for ensuring data availability.

For Python checkout:
[https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqa2FSalVTRVVyWjJOZVk3M1FaMG5Gd0ZwSDJQd3xBQ3Jtc0ttb0NVcmxqdUpmNnEyN2hfR3Q4X1BtMTRyRTd3TWZQaDRJZFdHdlJURWg1c1NXc2xCM2lWRFRxdzRkUVJnZ2g0SmxqajVCYnVQOTNHVEVnSDRRXy04X2NoTUI1OGlTNWJLbFZ1TTltTzdWRmxfbmFLbw&q=https%3A%2F%2Fgithub.com%2FIntelRealSense%2Flibrealsense%2Ftree%2Fmaster%2Fwrappers%2Fpython&stzid=Ugyncirf_KvRWw93jGN4AaABAg.9yAP6rykiSf9yEJ__Rs8Js)
AND/OR
[https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/opencv_viewer_example.py](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbmNJUE8xNFBKRkNNbXFteTY2UjFHSEdrUHh1UXxBQ3Jtc0ttVGNPZ0FHY0VBa00zUG5OeHFCREREbUR0QXNpWW5nQ1BNSzRhVHBLUkFBUHlNMVZ5UGZDR0Z5aTJoYlJFT2lBaUhRb0ZLNnlyM0M1eV9TYWlJV0VVck8wMWpOS2xVbkp2V2RWZWpKQmxtaFBvZVZtcw&q=https%3A%2F%2Fgithub.com%2FIntelRealSense%2Flibrealsense%2Fblob%2Fmaster%2Fwrappers%2Fpython%2Fexamples%2Fopencv_viewer_example.py&stzid=Ugyncirf_KvRWw93jGN4AaABAg.9yAP6rykiSf9yEJ__Rs8Js)

For C++ checkout: [https://dev.intelrealsense.com/docs/opencv-wrapper](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbktLVDNqN2RTajRvRjRzRTdZSFpsZ01RcHVxUXxBQ3Jtc0ttQjJPdHhaWHVXTThLeE9lVXBTREMweUt5THotV1NPUmxXcDVIY3VXYk5lblV3VzlJZG42b2NIN3pfOG9pMUpLOEQzTUdacDZxU1puNU9Ra1VRTmtVZm1ZSjhuLW5qNHJYSHYwMzhuVi1ZV0lHOTNPOA&q=https%3A%2F%2Fdev.intelrealsense.com%2Fdocs%2Fopencv-wrapper&stzid=Ugyncirf_KvRWw93jGN4AaABAg.9yAP6rykiSf9yEJ__Rs8Js)

Hope this helps and all the best for your project!
